theme: jekyll-theme-cayman
title: Okay Result
description: > # this means to ignore newlines until "show_excerpts:"
www.okayresult.com
google_analytics: UA-NNNNNNNN-N
plugins:
 - jekyll-feed
 - jekyll-seo-tag
